# This is a basic workflow to help you get started with Actions

name: Push to Production

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  update_master:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: run_curl
      shell: bash
      run: | 
        resp=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH --url ${{ secrets.SHARD_REPO_URL }} -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" -H "Content-Type: application/json" -d '{ "branch": "main" }'); echo $resp; if [ $resp != "200" ] ; then echo "failed"; exit -1; else echo "worked"; fi
        
      